Name: cdk-deployment
RunMode: SUPERSEDED
SchemaVersion: "1.0"
Triggers:
  - Type: PUSH
    Branches:
      - main
      - feature/2-initial-cdk-code
      - feature/2-initial-cdk-code
    FilesChanged:
      - ".*"
Actions:
  BuildAndTestCDKApp:
    Identifier: aws/build@v1
    Inputs:
      Sources:
        - WorkflowSource
    Outputs:
      AutoDiscoverReports:
        Enabled: true
        ReportNamePrefix: rpt
        IncludePaths:
          - ./coverage/lcov.info
    Configuration:
      Steps:
        - Run: npm install
        - Run: npm run build
    Compute:
      Type: Lambda
  DeployCDKApp:
    DependsOn:
      - BuildAndTestCDKApp
    Actions:
      DeployMessagingService:
        Identifier: aws/github-actions-runner@v1
        Compute:
          Type: EC2
        Inputs:
          Sources:
            - WorkflowSource
          Variables:
            - Name: AWS_REGION
              Value: eu-central-1
        Configuration:
          Steps:
            - run: npm install
            - run: npm run deploy cicdonaws-apidata-service -- --require-approval never
        Environment:
          Connections:
            - Role: CodeCatalystPreviewDevelopmentAdministrator-g5ghp1
              Name: "215381813818"
          Name: communitybuilders-dev
      DeployFrontend:
        Identifier: aws/github-actions-runner@v1
        Compute:
          Type: EC2
        Inputs:
          Sources:
            - WorkflowSource
          Variables:
            - Name: AWS_REGION
              Value: eu-central-1
        Configuration:
          Steps:
            - run: npm install
            - run: npm run deploy cicdonaws-frontend -- --require-approval never
        Environment:
          Connections:
            - Role: CodeCatalystPreviewDevelopmentAdministrator-g5ghp1
              Name: "215381813818"
          Name: communitybuilders-dev
  AWSCDKbootstrap_01:
    Identifier: aws/cdk-bootstrap@v1
    Configuration:
      Region: eu-central-1
    Compute:
      Type: Lambda
    Environment:
      Connections:
        - Role: CodeCatalystPreviewDevelopmentAdministrator-g5ghp1
          Name: "215381813818"
      Name: communitybuilders-dev
    Inputs:
      Sources:
        - WorkflowSource
