Name: cdk-deployment
RunMode: SUPERSEDED
SchemaVersion: "1.0"
Triggers:
  - Type: PUSH
    Branches:
      - main
      - feature/2-initial-cdk-code
    FilesChanged:
      - "cdk-app/.*"      
Actions:
  BuildAndTestCDKApp:
    Identifier: aws/build@v1
    Inputs:
      Sources:
        - WorkflowSource
    Outputs:
      AutoDiscoverReports:
        Enabled: true
        ReportNamePrefix: rpt
        IncludePaths:
          - ./coverage/lcov.info
    Configuration:
      Steps:
        - Run: npm install
        - Run: npm run build
    Compute:
      Type: Lambda
  DeployCDKApp:
    DependsOn:
      - BuildAndTestCDKApp
    Actions:
      DeployMessagingService:
        Identifier: aws/github-actions-runner@v1
        Compute:
          Type: EC2
        Inputs:
          Sources:
            - WorkflowSource
          Variables:
            - Name: AWS_REGION
              Value: eu-central-1
        Configuration:
          Steps:
            - run: cd npm install
            - run: cd npm run deploy cicdonaws-apidata-service --
                --require-approval never
        Environment:
          Connections:
            - Role: CodeCatalystPreviewDevelopmentAdministrator-rnxk91
              Name: johannes-playground
          Name: development     
      DeployFrontend:
        Identifier: aws/github-actions-runner@v1
        Compute:
          Type: EC2
        Inputs:
          Sources:
            - WorkflowSource
          Variables:
            - Name: AWS_REGION
              Value: eu-central-1
        Configuration:
          Steps:
            - run: cd cdk-app; npm install
            - run:
                cd cdk-app; npm run deploy cicdonaws-frontend -- --require-approval
                never
        Environment:
          Connections:
            - Role: CodeCatalystPreviewDevelopmentAdministrator-rnxk91
              Name: johannes-playground
          Name: development
